version: '3.8'
services:
  postgres-lab-2:
    container_name: postgres-lab-2
    image: postgres:16
    environment:
      POSTGRES_DB: lab2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-lab:/data/postgres
    restart: always

  http-server:
    image: smeloved/http-server:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-lab-2:5432/lab2
      - WEB_SOCKET_URL=ws://websocket-server:8081
    depends_on:
      - postgres-lab-2

  websocket-server:
    image: smeloved/websocket-server:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres-lab-2
