spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lab2}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true

scrapping:
  base-url: https://www.pandashop.md

logging:
  level:
    root: INFO

