spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lab2}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true

scrapping:
  base-url: https://www.pandashop.md

document:
  file-storage-path: http-server/src/main/resources/storage

websocket:
  base-url: ${WEB_SOCKET_URL:ws://localhost:8081}

logging:
  level:
    root: DEBUG
server:
  port: 8082

raft:
  node-id: ${RAFT_NODE_ID:1}
  cluster-nodes: ${RAFT_CLIENT_NODES:127.0.0.1:5001,127.0.0.1:5002,127.0.0.1:5003}
  udp-port: ${RAFT_UDP_PORT:5001}
